// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKuXzEuVQDL1BdO-CDfqCF9id-UBFDsws',
    appId: '1:89249875327:web:41ac65ca093a186574c64a',
    messagingSenderId: '89249875327',
    projectId: 'login-a3631',
    authDomain: 'login-a3631.firebaseapp.com',
    storageBucket: 'login-a3631.appspot.com',
    measurementId: 'G-9LE2F93L2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhTIKtIHZ-HycqG8CFTH0UWFzSKdaubVs',
    appId: '1:89249875327:android:77b2eef10c07a68c74c64a',
    messagingSenderId: '89249875327',
    projectId: 'login-a3631',
    storageBucket: 'login-a3631.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvlthPYoJ2h22CEshaHSpEal8ukAkxHPs',
    appId: '1:89249875327:ios:6abde6c00e17c3a574c64a',
    messagingSenderId: '89249875327',
    projectId: 'login-a3631',
    storageBucket: 'login-a3631.appspot.com',
    iosClientId: '89249875327-1osibkh06qo0nmq3e8gqshlsk9mfg5u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmailSend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvlthPYoJ2h22CEshaHSpEal8ukAkxHPs',
    appId: '1:89249875327:ios:00faa592f32209b474c64a',
    messagingSenderId: '89249875327',
    projectId: 'login-a3631',
    storageBucket: 'login-a3631.appspot.com',
    iosClientId: '89249875327-4ld0vrvrkag11c1b8v3nv1cfp44fubp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmailSend.RunnerTests',
  );
}
